[workspace]

members = [
    "json_path",
    "redis_json"
]

[workspace.dependencies]
ijson = "0.1.3"
serde_json = { version="1.0", features = ["unbounded_depth"]}
serde = "1.0"

[workspace.package]
edition = "2021"