[workspace]

members = [
    "json_path",
    "redis_json"
]

[workspace.dependencies]
ijson = { git="https://github.com/RedisJSON/ijson", rev="e0119ac74f6c4ee918718ee122c3948b74ebeba8", default_features=false}
serde_json = { version = "1", features = ["unbounded_depth"]}
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
bson = "0.14"

[workspace.package]
edition = "2021"
repository = "https://github.com/RedisJSON/RedisJSON"
license = "LicenseRef-RSALv2 OR SSPL-1.0"

[profile.release]
debug = 1
