[package]
name = "redisjson"
version = "99.99.99"
authors = ["Gavrie Philipson <gavrie@redislabs.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "rejson"

[dependencies]
log = "0.4"
bson = "0.14"
ijson = "0.1.3"
serde_json = "1.0"
serde = "1.0"
libc = "0.2"
jsonpath_lib = { git = "https://github.com/RedisJSON/jsonpath.git", branch = "generic_json_path" }
redis-module = { version="0.26", features = ["experimental-api"]}
itertools = "0.10.1"
[features]
# Workaround to allow cfg(feature = "test") in redismodue-rs dependencies:
# https://github.com/RedisLabsModules/redismodule-rs/pull/68
# This requires running the tests with `--features test`
test = ["redis-module/test"]
as-library = []

[profile.release]
debug = 1
