[workspace]
resolver = "2"

members = [
    "json_path",
    "redis_json"
]

[workspace.dependencies]
ijson = { git="https://github.com/RedisJSON/ijson", rev="e0119ac74f6c4ee918718ee122c3948b74ebeba8", default_features=false}
serde_json = { version="1.0", features = ["unbounded_depth"]}
# DO NOT CHANGE to avoid security issues. This exact version
# specification is required for the second level dependencies
# to use exactly this version too, so that the dependencies of
# this project will not be able to compromise it.
#serde = { version = "=1.0.203", features = ["derive"] }
#serde_derive = "=1.0.203"
#bson = "2"
#time = "0.3.36"


proc-macro2 = "1.0.83"
unicode-ident = "1.0.12"
cfg-if = "1.0.0"
libc = "0.2.155"
memchr = "2.7.2"
autocfg = "1.3.0"
serde = "1.0.171"
once_cell = "1.19.0"
quote = "1.0.36"
version_check = "0.9.4"
syn = "2.0.65"
lazy_static = "1.4.0"
thiserror = "1.0.61"
ahash = "0.8.11"
hashbrown = "0.14.5"
aho-corasick = "1.1.3"
getrandom = "0.2.15"
lock_api = "0.4.12"
radium = "0.7.0"
zerocopy = "0.7.34"
equivalent = "1.0.1"
ucd-trie = "0.1.6"
regex-syntax = "0.8.3"
itoa = "1.0.11"
parking_lot_core = "0.9.10"
indexmap = "2.2.6"
rand_core = "0.6.4"
regex-automata = "0.4.6"
ryu = "1.0.18"
smallvec = "1.13.2"
ppv-lite86 = "0.2.17"
tap = "1.0.1"
scopeguard = "1.2.0"
time-core = "0.1.1"
time-macros = "0.2.12"
wyz = "0.5.1"
regex = "1.10.4"
serde_derive = "1.0.171"
thiserror-impl = "1.0.61"
rand_chacha = "0.3.1"
deranged = "0.3.11"
pest = "2.7.10"
log = "0.4.21"
funty = "2.0.0"
bitvec = "1.0.1"
pest_meta = "2.7.10"
time = "0.3.26"
pest_generator = "2.7.10"
dashmap = "5.5.3"
rand = "0.8.5"
#hashbrown = "0.13.2"
hex = "0.4.3"
base64 = "0.13.1"
pest_derive = "2.7.10"
is-terminal = "0.4.12"
humantime = "2.1.0"
termcolor = "1.4.1"
uuid = "1.8.0"
serde_bytes = "0.11.14"
env_logger = "0.10.2"
glob = "0.3.1"
prettyplease = "0.2.20"
rustix = "0.38.34"
clang-sys = "1.7.0"
bson = "2.10.0"
#syn = "1.0.109"
linux-raw-sys = "0.4.14"
minimal-lexical = "0.2.1"
bitflags = "2.5.0"
cc = "1.0.98"
json_path = "0.1.0"
nom = "7.1.3"
num-traits = "0.2.19"
libloading = "0.8.3"
home = "0.5.9"
either = "1.12.0"
bindgen = "0.66.1"
which = "4.4.2"
cexpr = "0.6.0"
memoffset = "0.7.1"
shlex = "1.3.0"
rustc-hash = "1.1.0"
peeking_take_while = "0.1.2"
unicode-xid = "0.0.4"
#bitflags = "1.3.2"
rustversion = "1.0.17"
lazycell = "1.3.0"
synom = "0.11.3"
backtrace = "0.3.71"
#quote = "0.3.15"
adler = "1.0.2"
gimli = "0.28.1"
miniz_oxide = "0.7.3"
#syn = "0.11.11"
#num-traits = "0.1.43"
linkme-impl = "0.3.26"
addr2line = "0.21.0"
object = "0.32.2"
heck = "0.4.1"
pin-utils = "0.1.0"
rustc-demangle = "0.1.24"
linkme = "0.3.26"
nix = "0.26.4"
strum_macros = "0.24.3"
redis-module = "2.0.7"
enum-primitive-derive = "0.1.2"
redis-module-macros-internals = "2.0.7"
serde_syn = "0.1.0"
redis-module-macros = "2.0.7"
itertools = "0.12.1"

[workspace.package]
edition = "2021"
repository = "https://github.com/RedisJSON/RedisJSON"
license = "Redis Source Available License 2.0 (RSALv2) or the Server Side Public License v1 (SSPLv1)"

[profile.release]
debug = 1
