[package]
name = "redisjson"
version = "99.99.99"
authors = ["Gavrie Philipson <gavrie@redislabs.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
name = "rejson"

[dependencies]
log = "0.4"
bson = "0.14"
serde_json = "1.0"
serde = "1.0"
libc = "0.2"
jsonpath_lib = { git = "https://github.com/RedisJSON/jsonpath.git", branch = "generic_json_path" }
#redis-module = { version="0.22", features = ["experimental-api"]}
redis-module = { git = "https://github.com/RedisLabsModules/redismodule-rs.git", branch = "omer-short-read", features = ["experimental-api"] }
[features]
# Workaround to allow cfg(feature = "test") in redismodue-rs dependencies:
# https://github.com/RedisLabsModules/redismodule-rs/pull/68
# This requires running the tests with `--features test`
test = ["redis-module/test"]
as-library = []
