[package]
name = "redisjson"
version = "1.9.0"
authors = ["Gavrie Philipson <gavrie@redislabs.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "rejson"

[dependencies]
bson = "0.14"
serde_json = "1.0"
serde = "1.0"
libc = "0.2"
jsonpath_lib = { git="https://github.com/RedisJSON/jsonpath.git", branch="public-parser" }
redis-module = { version="0.9.1", features = ["experimental-api"]}
redisearch_api = "0.4.2"

[features]
# Workaround to allow cfg(feature = "test") in redismodue-rs dependencies:
# https://github.com/RedisLabsModules/redismodule-rs/pull/68
# This requires running the tests with `--features test`
test = ["redis-module/test"]
