version: 2.1

commands:
  abort_for_docs:
    steps:
      - run:
          name: Avoid tests for docs
          command: |
            if [[ $CIRCLE_BRANCH == *_docs ]]; then
              echo "Identifies as documents PR, no testing required"
              circleci step halt
            fi

  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [[ -n "$CIRCLE_PR_NUMBER" ]]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi

  setup_executor:
    steps:
      - run:
          name: Setup executor
          command: |
            apt-get -qq update
            apt-get -q install -y git openssh-client curl ca-certificates make tar gzip
            bash <(curl -fsSL https://get.docker.com)
      - setup_remote_docker:
          docker_layer_caching: true

  setup_automation:
    steps:
      - run:
          name: Setup automation
          command: |
            git submodule update --init deps/readies
            ./deps/readies/bin/getpy3

  checkout_all:
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive

  build_steps:
    parameters:
      build_params:
        type: string
        default: ""
      test_params:
        type: string
        default: ""
      redis_version:
        type: string
        default: "6"
      getredis_params:
        type: string
        default: ""
    steps:
      - abort_for_docs
      - checkout_all
      - run:
          name: Setup automation and install dependencies
          command: |
            ./deps/readies/bin/getpy3
            ./system-setup.py
            source $HOME/.cargo/env
            rustc --version
            cargo --version
            rustup --version
      - run:
          name: Install Redis
          command: |
            bash -l -c "./deps/readies/bin/getredis -v <<parameters.redis_version>> --force <<parameters.getredis_params>>"
            redis-server --version
      - restore_cache:
          keys:
            - v2-dependencies-{{ arch }}-{{ checksum "Cargo.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Check formatting
          command: bash -l -c "make lint"
      - run:
          name: Build debug
          command: bash -l -c "make build DEBUG=1 <<parameters.build_params>>"
      - run:
          name: Build release
          command: bash -l -c "make build pack <<parameters.build_params>>"
      - run:
          name: Run all tests
          command: bash -l -c "make pytest"
      - save_cache:
          key: v2-dependencies-{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"
      - store_artifacts:
          path: tests/pytest/logs

  platforms_build_steps:
    parameters:
      platform:
        type: string
    steps:
      - abort_for_docs
      - setup_executor
      - checkout_all
      - setup_automation
      - run:
          name: Build for platform
          command: |
            cd build/platforms
            make build OSNICK=<<parameters.platform>> ARTIFACTS=1 TEST=1 SHOW=1
      - early_return_for_forked_pull_requests
      - run:
          name: Build for platform (publish)
          command: |
            docker login -u redisfab -p $DOCKER_REDISFAB_PWD
            cd build/platforms
            make publish OSNICK=<<parameters.platform>> OFFICIAL=0 SHOW=1 VERBOSE=1
      - persist_to_workspace:
          root: bin/
          paths:
            - 'snapshots/*.zip'
            - 'snapshots/*.tgz'
            - '*.zip'
            - '*.tgz'

jobs:
  build:
    docker:
      - image: redisfab/rmbuilder:6.2.1-x64-buster
    steps:
      - build_steps

  platforms_build:
    parameters:
      platform:
        type: string
    docker:
      - image: debian:buster
    steps:
      - platforms_build_steps:
          platform: <<parameters.platform>>

  macos:
    macos:
      xcode: 11.3.0
    steps:
      - build-steps


  deploy_artifacts:
    parameters:
      location:
        type: string
        default: ""
    docker:
      - image: redisfab/rmbuilder:6.2.1-x64-buster
    steps:
      - abort_for_docs
      - early_return_for_forked_pull_requests
      - attach_workspace:
          at: workspace
      - run:
          name: Deploy to S3
          command: |
            cd "workspace/artifacts/<<parameters.location>>"
            du -ah --apparent-size *
            if [[ -z <<parameters.location>> ]]; then
                path="/"
            else
                path="<<parameters.location>>/"
            fi
            for f in `ls *.zip *.tgz`; do
              aws s3 cp $f s3://redismodules/$PACKAGE_NAME/$path --acl public-read
            done

  release_automation:
    docker:
      - image: redisfab/rmbuilder:6.2.1-x64-buster
    steps:
      - checkout
      - setup_automation
      - run:
          name: Run QA Automation
          command: MODULE_VERSION=$CIRCLE_TAG VERBOSE=1 TEST=release ./tests/qa/run

  nightly_automation:
    docker:
      - image: redisfab/rmbuilder:6.2.1-x64-buster
    steps:
      - checkout
      - setup_automation
      - run:
          name: Run QA Automation
          command: MODULE_VERSION=$CIRCLE_BRANCH VERBOSE=1 TEST=nightly QUICK=1 ./tests/qa/run


on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

never: &never
  filters:
    branches:
      ignore: /.*/
    tags:
      ignore: /.*/

on-master: &on-master
  filters:
    branches:
      only: master
    tags:
      ignore: /.*/

on-integ-branch: &on-integ-branch
  filters:
    branches:
      only:
        - master
        - /^\d+\.\d+.*$/
        - /^feature-.*$/
    tags:
      ignore: /.*/

not-on-integ-branch: &not-on-integ-branch
  filters:
    branches:
      ignore:
        - master
        - /^\d+\.\d+.*$/
        - /^feature-.*$/
    tags:
      ignore: /.*/

on-version-tags: &on-version-tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v[0-9].*/

on-integ-and-version-tags: &on-integ-and-version-tags
  filters:
    branches:
      only:
        - master
        - /^\d+\.\d+.*$/
        - /^feature-.*$/
    tags:
      only: /^v[0-9].*/


workflows:
  version: 2
  build_and_package:
    jobs:
      - build:
          <<: *not-on-integ-branch
      - platforms_build:
          context: common
          #@@ <<: *on-integ-and-version-tags
          <<: *on-integ-branch
          matrix:
            parameters:
              platform: [focal, bionic, xenial, centos7]
      - deploy_artifacts:
      - build-macos:
          #@@ <<: *on-integ-and-version-tags
          <<: *on-any-branch
          name: deploy_snapshot
          location: snapshots
          context: common
          <<: *on-integ-branch
          requires:
            - platforms_build
      - deploy_artifacts:
          name: deploy_release
          context: common
          <<: *on-version-tags
          requires:
            - platforms_build
      - release_automation:
          <<: *on-version-tags
          requires:
            - deploy_release

  nightly:
    triggers:
      - schedule:
          cron: "07 20 * * *"
          filters:
            branches:
              only: master
    jobs:
      - nightly_automation
