version: 2.1

commands:
  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi

  setup-automation:
    steps:
      - run:
          name: Setup automation
          command: |
            (mkdir -p deps; cd deps; git clone https://github.com/RedisLabsModules/readies.git)
            ./deps/readies/bin/getpy2
            python2 -m pip install -r ./deps/readies/paella/requirements.txt

  benchmark-steps:
    parameters:
      github_actor:
        type: string
        default: $CIRCLE_USERNAME
      module_path:
        type: string
        default: ../../src/rejson.so
    steps:
      - run:
          name: Install remote benchmark tool dependencies
          command: |
            mkdir -p /workspace
            TF_EXE_FILE_NAME=/workspace/terraform ./tests/benchmarks/remote/install_deps.sh
      - run:
          name: Install remote benchmark python dependencies
          command: python3 -m pip install -r ./tests/benchmarks/requirements.txt
      - run:
          name: Run CI benchmarks on aws
          timeout: 60m
          no_output_timeout: 30m
          command: |
            cd ./tests/benchmarks
            export AWS_ACCESS_KEY_ID=$PERFORMANCE_EC2_ACCESS_KEY
            export AWS_SECRET_ACCESS_KEY=$PERFORMANCE_EC2_SECRET_KEY
            export AWS_DEFAULT_REGION=$PERFORMANCE_EC2_REGION
            export EC2_PRIVATE_PEM=$PERFORMANCE_EC2_PRIVATE_PEM
            redisbench-admin run-remote \
              --terraform_bin_path /workspace/terraform \
              --module_path << parameters.module_path >> \
              --github_actor << parameters.github_actor >> \
              --github_repo $CIRCLE_PROJECT_REPONAME \
              --github_org $CIRCLE_PROJECT_USERNAME \
              --github_sha $CIRCLE_SHA1 \
              --github_branch $CIRCLE_BRANCH \
              --upload_results_s3 \
              --triggering_env circleci \
              --push_results_redistimeseries

jobs:
  build:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    steps:
      - checkout

      - run: 
          name: Checkout submodules
          command: git submodule update --init --recursive
      - run:
          name: Build
          command: make -j `nproc`
      - run:
          name: Test
          command: make test
      - early_return_for_forked_pull_requests
      - run:
          name: Persist Artifacts
          command: |
            mkdir -p /workspace/build
            cp src/$MODULE_ARTIFACT /workspace/
            cp ramp.yml /workspace/

      - persist_to_workspace:
          root: /workspace
          paths:
            - '*.so'
            - ramp.yml
            - build
  package_branch:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Package
          command: >-
            python -m RAMP.ramp pack -m /workspace/ramp.yml -o
            /workspace/build/$PACKAGE_NAME.{os}-{architecture}.$CIRCLE_BRANCH.zip
            /workspace/$MODULE_ARTIFACT
      - persist_to_workspace:
          root: /workspace
          paths:
            - build
      - store_artifacts:
          path: /workspace/build

  package_release:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Package
          command: >-
            python -m RAMP.ramp pack -m /workspace/ramp.yml -o
            /workspace/build/$PACKAGE_NAME.{os}-{architecture}.{semantic_version}.zip
            /workspace/$MODULE_ARTIFACT
      - run:
          name: Package
          command: >-
            python -m RAMP.ramp pack -m /workspace/ramp.yml -o
            /workspace/build/$PACKAGE_NAME.{os}-{architecture}.latest.zip
            /workspace/$MODULE_ARTIFACT
      - persist_to_workspace:
          root: /workspace
          paths:
            - build
      - store_artifacts:
          path: /workspace/build

  deploy_branch:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy to S3
          command: |
            aws s3 cp /workspace/build/ s3://redismodules/$PACKAGE_NAME/ --acl public-read --recursive --exclude "*" --include "*.zip"

  deploy_release:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy to S3
          command: |
            aws s3 cp /workspace/build/ s3://redismodules/$PACKAGE_NAME/ --acl public-read --recursive --exclude "*" --include "*.zip"

  release_automation:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    steps:
      - checkout
      - setup-automation
      - run:
          name: Run QA Automation
          command: MODULE_VERSION=$CIRCLE_TAG VERBOSE=1 TEST=release ./tests/qa/run

  nightly_automation:
    docker:
      - image: redisfab/rmbuilder:6.0.9-x64-buster
    steps:
      - checkout
      - setup-automation
      - run:
          name: Run QA Automation
          command: MODULE_VERSION=$CIRCLE_BRANCH VERBOSE=1 TEST=nightly QUICK=1 ./tests/qa/run

  performance-automation:
    docker:
      - image: redisfab/rmbuilder:6.2.1-x64-bionic
    steps:
      - early_return_for_forked_pull_requests
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init --recursive
      - run:
          name: Build
          command: make -j `nproc`
      - benchmark-steps

on-any-branch: &on-any-branch
  filters:
    branches:
      only: /.*/
    tags:
      only: /.*/

never: &never
  filters:
    branches:
      ignore: /.*/
    tags:
      ignore: /.*/

on-master: &on-master
  filters:
    branches:
      only: master

on-version-tags: &on-version-tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v[0-9].*/

on-master-and-version-tags: &on-master-and-version-tags
  filters:
    branches:
      only:
        - master
    tags:
      only: /^v[0-9].*/

on-integ-and-version-tags: &on-integ-and-version-tags
  filters:
    branches:
      only:
        - master
        - /^\d+\.\d+.*$/
        - /^feature-.*$/
    tags:
      only: /^v[0-9].*/

workflows:
  version: 2
  build_and_package:
    jobs:
      - build:
          <<: *on-any-branch
      - package_branch:
          <<: *on-master
          requires:
            - build
      - package_release:
          context: common
          <<: *on-version-tags
          requires:
            - build
      - deploy_branch:
          context: common
          <<: *on-master
          requires:
            - package_branch
      - release_automation:
          context: common
          requires:
            - deploy_branch
      - deploy_release:
          context: common
          <<: *on-version-tags
          requires:
            - package_release
      - performance-automation:
          <<: *on-integ-and-version-tags
          context: common

  nightly:
    triggers:
      - schedule:
          cron: "07 20 * * *"
          <<: *on-master
    jobs:
      - nightly_automation
