[package]
name = "redisjson"
version = "99.99.99"
authors = ["Guy Korland <guy.korland@redis.com>", "Meir Shpilraien <meir@redis.com>", "Omer Shadmi <omer.shadmi@redis.com>"]
edition = "2021"
description = "JSON data type for Redis"
repository = "https://github.com/RedisJSON/RedisJSON"
readme = "README.md" 
license = "Redis Source Available License 2.0 (RSALv2) or the Server Side Public License v1 (SSPLv1)"
keywords = ["redis", "json", "plugin"]
categories = ["database-implementations"]

[lib]
crate-type = ["cdylib", "rlib"]
name = "rejson"

[dev-dependencies]
env_logger = "0.10.0"
#redis-module = { version="1.0", features = ["experimental-api", "test"]}

[dependencies]
bitflags = "1.3"
bson = "0.14"
ijson = "0.1.3"
serde_json = { version="1.0", features = ["unbounded_depth"]}
serde = "1.0"
libc = "0.2"
redis-module = { version="1.0", features = ["experimental-api"]}
itertools = "0.10"
json_path = {path="../json_path"}

[features]
# Workaround to allow cfg(feature = "test") in redismodue-rs dependencies:
# https://github.com/RedisLabsModules/redismodule-rs/pull/68
# This requires running the tests with `--features test`
test = ["redis-module/test"]
as-library = []

[profile.release]
debug = 1
