name: code coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        make setup
        rustup toolchain install nightly
        rustup default nightly
        rustup component add llvm-tools-preview        
    - name: Build
      run: |
        export RUSTFLAGS="-Zinstrument-coverage"
        cargo build --all --all-targets --verbose
    - name: Run tests
      run: |
        cargo install grcov
        export LLVM_PROFILE_FILE="your_name-%p-%m.profraw"
        MODULE=~/redislabsmodules/rejson/target/debug/librejson.so ./tests/pytest/tests.sh
    - name: Upload coverage
      run: bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov)
        


      
