name: code coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all --all-targets --verbose
    - name: Run tests
      run: |
        sudo apt install kcov
        cargo install cargo-kcov
        cargo kcov --features test --all --verbose
    - name: Upload coverage
      run: bash <(curl -s https://codecov.io/bash)
        


      
