name: Pull Request Flow

# Documentation: https://redislabs.atlassian.net/wiki/spaces/DX/pages/3967844669/RediSearch+CI+refactor

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review] # Defaults + ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-latest-redis-tag:
    uses: ./.github/workflows/task-get-latest-tag.yml
    with:
      repo: redis/redis
      prefix: '7.4'



  basic-test:
    needs: [get-latest-redis-tag]
    uses: ./.github/workflows/task-test.yml
    with:
      env: ubuntu-latest
      get-redis: ${{ needs.get-latest-redis-tag.outputs.tag }}
    secrets: inherit

  coverage:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/flow-coverage.yml
    secrets: inherit

  sanitize:
    needs: [get-latest-redis-tag]
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/flow-sanitizer.yml
    secrets: inherit
    with:
      get-redis: ${{ needs.get-latest-redis-tag.outputs.tag }}

  pr-validation:
    needs:
      - get-latest-redis-tag
      - basic-test
      - coverage
      - sanitize
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
