name: freebsd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        sync: rsync
        prepare: pkg install -y bash lang/rust devel/llvm-devel
        run: >
          cargo build --all --all-targets --verbose 
          rustup target add i686-unknown-freebsd
          cargo build --all --all-targets --verbose --target i686-unknown-freebsd
