name: build for mariner2

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l -o pipefail {0}
    container:
      image: mcr.microsoft.com/cbl-mariner/base/core:2.0
    steps:
      - name: Install prereqs
        run: |
          tdnf install --noplugins --skipsignature -y ca-certificates
          tdnf install -q -y git
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          bash .install/mariner2.sh
      - name: Get redis latest
        run: |
          bash .install/get_redis.sh
      - name: Build
        run: |
          make build
      - name: Test
        run: |
          make test
      - name: Pack module
        run: |
          make pack BRANCH=${{ github.ref_name }}
      - name: Upload to staging
        run: |
          make upload-release SHOW=1 STAGING=1 FORCE=1 VERBOSE=1

# todo: upload artifacts to S3
