name: build for mariner2

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l -o pipefail {0}
    container:
      image: mcr.microsoft.com/cbl-mariner/base/core:2.0
    steps:
      - run: |
          tdnf install --skipsignature -y git
      - name: checkout
        uses: actions/checkout@v4
      - run: |
          git config --global --add safe.directory '*'
          git submodule update --init --recursive
      - name: install dependencies
        run: |
          .install/mariner2.sh
      - name: get redis latest
        run: |
          .install/get_redis.sh
      - name: build and test
        run: |
          make test
      - name: pack module
        run: |
          make pack

# todo: upload artifacts to S3
